name: Docker Alpine Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Run alpine image
      run: |
        docker pull alpine
        docker run --rm alpine /bin/sh -c "echo Hello alpine"

    - name: Show secret
      run: echo "My_Secret: ${{ secrets.MY_SECRET }}"
